---
- name: Get local interfaces
  set_fact:
    local_interfaces:  "{{ local_interfaces|default([]) + [hostvars[inventory_hostname]['ansible_' + item ]['device']] }}"
  loop: "{{ ansible_interfaces }}"
  when: |
   hostvars[inventory_hostname]['ansible_' + item ]['ipv4']['address'] is defined
    and
   hostvars[inventory_hostname]['ansible_' + item ]['type'] == 'ether'
    and
   hostvars[inventory_hostname]['ansible_' + item ]['ipv4']['address'] | ipaddr('private')

- name: Get local address
  set_fact:
    local_addresses:  "{{ local_addresses|default([]) + [hostvars[inventory_hostname]['ansible_' + item]['ipv4']['address'] + '/' + hostvars[inventory_hostname]['ansible_' + item]['ipv4']['netmask']] }}"
  loop: "{{ local_interfaces }}"
   
- name: Get neighbors list
  set_fact:
    neighbors:  "{{ neighbors|default([]) + [ item ] }}"
  loop: "{{ groups['routers'] }}"
  when: inventory_hostname != item

- name: Get neighbors local address
  set_fact:
    neighbors_local_addresses:  "{{ neighbors_local_addresses|default([]) + [hostvars[item]['local_addresses']] }}"
  loop: "{{ neighbors }}"
...