---
- name: restart zebra
  systemd:
    name: zebra
    state: restarted
    enabled: true
  ignore_errors: true  
  become: true

- name: restart ospfd
  systemd:
    name: ospfd
    state: restarted
    enabled: true
  ignore_errors: true  
  become: true
...
